/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import City from '../../../models/starter-scene.glb'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(City)
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.ground.geometry} material={materials['Material.010']} position={[1300.57, -0.08, -2894.07]} scale={-14809.02} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.main_tv.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.skyscreaper.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.lakes.geometry} material={materials['Material.007']} position={[0, 1.59, 0]} />
      <mesh geometry={nodes.Areaslanduse.geometry} material={materials['Material.009']} position={[0, 1.04, 0]} />
      <mesh geometry={nodes.Areasbuilding.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload(City)
